spring:
  application:
    name: currency-service



  datasource:
    url: jdbc:h2:file:~/currency_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  mvc:
    log-request-details: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


logging:
  level:
#    root: DEBUG
    org:
      springframework:
        web: DEBUG

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

#eureka:
#  client:
#    enabled: false

currency-service:
  history-days-count-default: 5
  history-days-count-limit: 7
  query-per-min-limit: 10
  currency-filter: eur, usd, cad
  coin-filter: bitcoin, ethereum, tether, binancecoin, usd-coin, ripple, staked-ether, cardano, dogecoin, solana,
    tron, litecoin, matic-network, polkadot, wrapped-bitcoin, shiba-inu, dai, avalanche-2, binance-usd, action-coin

