locale-service:
  geolite-db-filename: classpath:data/GeoLite2-Country.mmdb
  default-country-code: DE
  default-lang-code: de
  default-currency-code: EUR
  api-path: api/
  api-version: v1

spring:
  application:
    name: locale-service
  datasource:
    url: jdbc:h2:mem:locale_db;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

server:
  port: 8081

eureka:
  client:
    enabled: false