rate-gateway:
  default-country-code: DE
  default-lang-code: de
  default-currency-code: EUR
  current-rate-date-format: EEEE, dd MMM, yyyy HH:mm:ss
  history-rate-date-format: dd MMM, yyyy
  scaled-rate-precision: 6
  scaled-rate-scale: 2

spring:
  application:
    name: rate-gateway

  # Cache configuration
  cache:
    type: caffeine
    cache-names: rateCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3m

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

microservices:
  localeService:
    serviceName: locale-service
    protocol: http
    urlPath: /api/v1/
    currencyLocalesEndpoint: getCurrencyLocales
  currencyService:
    serviceName: currency-service
    protocol: http
    urlPath: /api/
    currentRateEndpoint: get-current-rate
    rateHistoryEndpoint: get-rate-history
    formRateEndpoint: get-form-rate
    supportedCoins: get-supported-coins
    loadHistoryEndpoint: load-history
    deleteRateHistoryEndpoint: delete-rate-history
